AWSTemplateFormatVersion: 2010-09-09

Description: Template for creating a new ec2 instance for the elb

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues: [ t2.micro ]
    ConstraintDescription: must be a valid EC2 instance type.

  LatestAmiId:
    Type: String
    Default: ami-00399ec92321828f5

  SecGroupId:
    Description: the id of the security group
    Type: String

Resources:

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      SecurityGroupIds:
        - !Ref SecGroupId
      KeyName: !Ref KeyName
      ImageId: !Ref LatestAmiId
      IamInstanceProfile: shaiEladProfileName
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            sleep 20
            sudo apt-get update
            sudo apt-get install python3-pip -y
            sudo apt-get install python3-flask -y
            sudo apt-get install redis-server -y
            sudo service redis-server start
            pip3 install redis
            git clone https://github.com/shaibrown5/cloud_computing.git
            cd cloud_computing
            pip3 install -r requirements.txt
            cd hw2
            python3 app.py

Outputs:
  InstanceId:
    Description: InstanceId of the created EC2 instance
    Value: !Ref 'EC2Instance'
  InstanceIP:
    Description: Public IP address of the created EC2 instance
    Value: !GetAtt [EC2Instance, PublicIp]
